prompts:
  persona_creation: >
    Given the topic [TOPIC],
    create a roundtable debate of different personas
    to show key perspectives on the issue. Output the
    personas as a list of JSON objects. Each JSON object
    should have the following structure:
    {{"title": <title of the Persona>,
    "description": <Brief Description of the Persona>,
    "emoji": <Single emoji representation of the perspective the persona represents>}}.
    Ensure that the output is formatted as a valid JSON.
    Please generate exactly [NUM_PERSONAS] personas.
  persona_addition: >
    Given the topic '[TOPIC]',
    we are creating a roundtable debate of different personas to show key perspectives
    on the issue. Currently, we have personas as follows: [CURRENT_PERSONAS]
    Please output exactly one additional persona. Your output should have the following JSON structure:
    {"title": <title of the Persona>,
    "description": <Brief Description of the Persona>,
    "emoji": <Single emoji representation of the perspective the persona represents>}.
    Ensure that the output is formatted as a valid JSON.
  debate_start: >
    You are in an roundtable debate on the topic [TOPIC].
    You are [NAME], who is [DESC]. 
    Please start the debate by concisely presenting your
    argument for your stance on the topic. [LIMITER]
  debate: >
    You are in a continuing roundtable debate on the topic [TOPIC].
    You are [NAME], who is [DESC]. 
    Here is the transcript of the debate so far\: [HISTORY]
    Please continue to debate the others, concisely supporting your stance on
    the topic. [LIMITER]
  response_length: >
    Please limit your response to [RESPONSE_LENGTH]. You may use bullet points in parts of your response for readability. Use markdown format.
  topics:
    - "Is cell phone radiation safe?"
    - "Should animals be used for scientific or commercial testing?"
    - "Should humans colonize space?"
    - "Should people become vegetarian?"
    - "Is vaping with E-cigarettes safe?"
    - "Should abortion be legal?"
    - "Should the Federal minimum wage be increased?"
    - "Should the Federal corporate income tax rate be raised?"
    - "Should the United States implement a universal basic income?"
    - "Should TikTok be banned in school?"
    - "Do violent video games contribute to youth violence?"
    - "Are the Olympic games an overall benefit for their host countries and cities?"
    - "Do standardized tests improve education in America?"
    - "Should K-12 students dissect animals in science classrooms?"
    - "Are single-gender schools better for students?"
  

debate_params:
  transcript_word_limit: 2500
  num_debate_rounds: 5
  num_personas: 5
  limit_response_length: true

  # string indicating to the LLM how long the response should be.
  response_length: '200 words'

  # enable_continuous_mode:
  # Whether we allow personas to reply to only the previous round's responses,
  # or to the most recent response in the current round.
  # If continuous mode is on:
  #       Round 1: A will talk, B will reply to A, C will reply to A and B
  #       Round 2: A will respond to B and C's responses, B will reply to A, etc
  # If continuous mode is off:
  #       Round 1: A will talk, B will talk, C will talk
  #       Round 2: A will reply to B and C, B will reply to A and C, C will
  #                reply to A and B (Each persona responds to all of last
  #                round's discussion)
  enable_continuous_mode: false

  # generate_personas:
  # Prompt an LLM to generate the personas or not. If not, we initialize
  # num_personas empty personas, and the user should edit their names/desc
  # in the UI.
  generate_personas: true

  # Not implemented yet
  enable_arbiter: false

llm_params:
  model_name: 'gpt-4'
  temperature: 0.9


ux_params:
  show_persona_desc: true

